# Generated by Django 5.2.5 on 2025-09-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='reservado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
