# Generated by Django 5.2.5 on 2025-09-19 18:33

import ingressos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0002_compra_reservado_ate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='reservado_ate',
            field=models.DateTimeField(default=ingressos.models.default_reserva),
        ),
    ]
