# Generated by Django 5.2.5 on 2025-09-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0003_alter_compra_reservado_ate'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pix_copia_cola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='pix_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
    ]
