# Generated by Django 5.2.5 on 2025-09-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0004_compra_pix_copia_cola_compra_pix_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_ingresso', models.DecimalField(decimal_places=2, default=50.0, max_digits=8)),
            ],
        ),
    ]
