# Generated by Django 5.2.5 on 2025-09-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0005_configuracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
    ]
