# Generated by Django 5.2.5 on 2025-09-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0006_compra_valor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='pix_copia_cola',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='pix_qrcode',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='reservado_ate',
        ),
        migrations.AddField(
            model_name='compra',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='compra',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
