# Generated by Django 5.2.5 on 2025-09-27 18:04

import ingressos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0007_remove_compra_criado_em_remove_compra_pix_copia_cola_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='reservado_ate',
            field=models.DateTimeField(default=ingressos.models.default_reserva),
        ),
        migrations.AlterField(
            model_name='compra',
            name='txid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
