# Generated by Django 5.2.5 on 2025-09-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0008_compra_pago_compra_reservado_ate_alter_compra_txid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='pix_copia_cola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='pix_qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='pix'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='reservado_ate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
