# Generated by Django 5.2.5 on 2025-09-28 00:32

import ingressos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingressos', '0009_compra_pix_copia_cola_compra_pix_qrcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='reservado_ate',
            field=models.DateTimeField(default=ingressos.models.default_reserva),
        ),
        migrations.AlterField(
            model_name='compra',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=10),
        ),
    ]
